" zg -> Add word to current language file.
" z2g -> Add word to current language file.

" =========================================================================
" Generated by Gemini, 2025-10-16 16:00:03 EDT
"
" Function: SetLocalSpell(lang_code)
" Description: Sets the buffer-local spellfile and spelllang options.
" Parameter: lang_code - The language code ('en', 'fr', etc.)
" Usage: :call SetLocalSpell('fr')
" =========================================================================
function! SetLocalSpell(lang_code) abort
    " 1. Enable local spell-checking
    setlocal spell

    " 2. Set the spell language (e.g., 'en_us', 'fr')
    " We use an if-else for specific dialects, otherwise use the code as is.
    if a:lang_code == 'en'
        let l:language = 'en_us'
    else
        let l:language = a:lang_code
    endif
    execute 'setlocal spelllang=' . l:language

    " 3. Define the custom spellfile location and name
    " Note: It is best practice to include the encoding in the filename.
    let l:spellfile_name = a:lang_code . '.utf-8.add'

    " Use a consistent directory for all spell files.
    " This example uses the default user directory for spell files:
    " ~/.vim/spell/ or ~/.config/nvim/spell/
    let l:spell_dir = expand('$HDVIM/spell')
    if !isdirectory(l:spell_dir)
        " Fallback for older Vim or different setup
        echo "Error:  Could not find spell directory:  " . l.spell_dir
        let l:spell_dir = expand('~/.vim/spell')
    endif

    let l:full_path = l:spell_dir . '/' . l:spellfile_name

    " Check if the directory exists and create it if not
    if !isdirectory(l:spell_dir)
        call mkdir(l:spell_dir, 'p')
    endif

    " 4. Define the file names
    " Lang-specific file is FIRST (zg/1zg)
    let l:lang_file = l:spell_dir . '/' . a:lang_code . '.utf-8.add'
    " Common file is SECOND (2zg)
    let l:common_file = l:spell_dir . '/intl.utf-8.add'

    " 5. Set the buffer-local spellfile with the order reversed
    let l:spellfiles = l:lang_file . ',' . l:common_file
    execute 'setlocal spellfile=' . l:spellfiles

    " echo 'Spell set to: ' . l:language . ' (Files: ' . l:spellfiles . ')'
    echo 'Spell set to: ' . l:language

endfunction

function! AddToSpellFile(filename) abort
    let word = expand('<cword>')
    let spell_dir = expand('$HDVIM/spell')
    let filepath = spell_dir . '/' . a:filename
    
    " Add the word and rebuild the spell file silently
    call writefile([word], filepath, 'a')
    silent! execute 'mkspell! ' . filepath
    echo 'Added "' . word . '" to ' . a:filename
endfunction

" Add word directly in the specified file.
nnoremap zig :call AddToSpellFile('intl.utf-8.add')<CR>
nnoremap zeg :call AddToSpellFile('en.utf-8.add')<CR>
nnoremap zfg :call AddToSpellFile('fr.utf-8.add')<CR>

" Switch mode ton english or french.
nmap <esc>e :call SetLocalSpell('en')<CR>
nmap <esc>f :call SetLocalSpell('fr')<CR>

"map <esc>s :set nospell<CR>